bot:
  enabled: false
  payment-notification:
    five-days-send-rule: "-"
    five-days-delete-rule: "-"
    one-day-send-rule: "-"
    one-day-delete-rule: "-"
  error-group-notification:
    enabled: true
    chat-id: -101909

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.36:///billing
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        formatSql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog.sql

logging:
  level:
    su.vshk.billing.bot.: debug
  file:
    name: